import { IAnalyticsArray } from './dataContext.types';

export const weekAnalyticsArray: IAnalyticsArray[] = [
	{
		numberOfTimePeriod: 1,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 2,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 3,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 4,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 5,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 6,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 7,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 8,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 9,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 10,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 11,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 12,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 13,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 14,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 15,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 16,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 17,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 18,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 19,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 20,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 21,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 22,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 23,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 24,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 25,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 26,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 27,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 28,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 29,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 30,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 31,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 32,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 33,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 34,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 35,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 36,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 37,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 38,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 39,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 40,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 41,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 42,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 43,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 44,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 45,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 46,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 47,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 48,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 49,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 50,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 51,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 52,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
];

export const monthlyAnalyticsArray: IAnalyticsArray[] = [
	{
		numberOfTimePeriod: 1,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 2,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 3,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 4,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 5,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 6,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 7,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 8,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 9,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 10,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 11,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 12,
		valueExpanse: 0,
		valueIncome: 0,
		date: undefined,
	},
];