import { IAnalyticsArray } from './dataContext.types';

export const weekAnalyticsArray: IAnalyticsArray[] = [
	{
		numberOfTimePeriod: 1,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 2,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 3,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 4,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 5,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 6,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 7,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 8,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 9,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 10,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 11,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 12,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 13,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 14,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 15,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 16,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 17,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 18,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 19,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 20,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 21,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 22,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 23,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 24,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 25,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 26,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 27,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 28,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 29,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 30,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 31,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 32,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 33,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 34,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 35,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 36,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 37,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 38,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 39,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 40,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 41,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 42,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 43,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 44,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 45,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 46,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 47,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 48,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 49,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 50,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 51,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 52,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
];

export const monthlyAnalyticsArray: IAnalyticsArray[] = [
	{
		numberOfTimePeriod: 1,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 2,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 3,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 4,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 5,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 6,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 7,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 8,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 9,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 10,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 11,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
	{
		numberOfTimePeriod: 12,
		valueExpense: 0,
		valueIncome: 0,
		date: undefined,
	},
];